### ISSUE TITLE
libupnp-1.8.4存在内存泄漏风险 - libupnp-1.8.4 has a memory leak risk

### ISSUE THREAD

**Issue by LancelotWG** [pupnp/pupnp#194]
https://github.com/pupnp/pupnp/blob/24dea1e70268112f30b0fdaa06f4c34fe559b8ca/upnp/src/api/upnpapi.c#L3332
https://github.com/pupnp/pupnp/blob/24dea1e70268112f30b0fdaa06f4c34fe559b8ca/upnp/src/api/upnpapi.c#L3342
libupnp-1.8.4版本中的libupnp-1.8.4\upnp\src\api\upnpapi.c文件3332行申请的内存仅在3342行错误返回时释放，后续函数返回均未释放；同时3342行的内存释放是否不彻底。

**Comment by mrjimenez** [comment]
Please allow me to leave the google translation here:

In the libupnp-1.8.4 version, the memory requested by line 3332 of the file libupnp-1.8.4\upnp\src\api\upnpapi.c is released only when the error returns at line 3342, and subsequent function returns are not released; at the same time, the memory at line 3342

**Comment by mrjimenez** [comment]
Hi LancelotWG,

First, just an aside: what you are pointing at is WIN32 code, are you able to compile and use libupnp with windows? There were some complaints in the forum about this platform not being supported, I would just like to hear your opinion on this issue.

You are correct. The code does not release the memory allocated by adapts and will certainly cause a memory leak.

I will fix it in master and 1.8.x.

Regards,
Marcelo.

**Comment by LancelotWG** [comment]
我本身没有用在win32上使用，只是最近在排查代码里的内存泄漏问题，刚好看到了，就来提一下；目前还在分析代码中的其他内存泄漏问题，刚好问一下，如果反复调用UpnpInit2()函数初始化upnp会不会引发内存泄漏，我从代码上来分析好像没有风险(非win32)，想请教一下作者有自己测试过这方面的可靠性吗？

translation by Baidu(Sorry, Google translation is disabled):
I didn't use it on Win32. I just recently checked the memory leak problem in the code. I just saw it and raised it. At present, I'm still analyzing other memory leaks in the code. I just want to ask whether memory leakage will be caused by repeatedly calling the upnpinit2() function to initialize UPnP. From the code analysis, it seems that there is no risk (non Win32). I would like to ask Has the author tested the reliability in this respect?

**Comment by mrjimenez** [comment]
Hi Lancelot,

Unfortunately I am not the author of this code and I have no way to test it. We would have to go through the history of the code in order to find who it was and contact him about your question.

Since this is an open source project, we accept many contributions both in the form of code, but in the form of reports from the users as well. If someone offers code that will work in a certain platform, there is no reason not to accept it. The community builds around it and should report the problems.

Thank you very much for your effort!

Best regards,
Marcelo.
