### ISSUE TITLE
Qt creator files in repository

### ISSUE THREAD

**Issue by ePirat** [pupnp/pupnp#198]
It seems a while ago Qt creator files were added in the repository?

Is there a specific reason this was done? I can see why it might be useful to people using Qt creator but if we include IDE-specific files this opens a can of worms where we stop, as everyone has their own favorite IDE. Additionally those files tend to quickly get out of date eventually as people who contribute do not necessarily use Qt creator so forget to update them.

**Comment by ePirat** [comment]
(especially annoying as its a load of files, not just one, and it clutters the repository root and some subfolders too, it even took me a while to figure out what those are at all as the file themselves have no hint they are related to Qt creator, I at first I thought they are used now somewhere in the build system…)

**Comment by whyman** [comment]
+1 from me.

**Comment by mrjimenez** [comment]
I agree, you certainly have a point. But I also have a point :)

I have always developed absolutely everything in vi. But lets get real: this is not even close to the level of productivity any modern IDE has. And the feature I miss the most is the compilation preview. That saves me a lot of time, not only because I compile less, but mainly because I can see my mistakes while I am with the fresh ideas thinking about the code, so the code comes out clean and correct the first time most of the time.

The "click to follow" from call to definition is also a very good feature, but we had it with ctags for a long time. It is not really the same thing, since it needs Makefile magic or equivalent in other build systems.

As a secondary bonus, we can easily format code and keep a uniform coding style. Some people may say it is bullshit, but these people usually don't read code as compulsively as I do.

I tried vscode a while ago, when I got involved with javascript and related stuff, and got very excited about it. But unfortunately I have not managed to make it work decently with autotools. VSCode is also a mess to work with kernel code, which is also a place where I spend hours of my work. QTCreator allows me to do both with relative ease, even though the price I pay is an IDE heavier than I would like.

That said, I think we can reach a middle term. They are not really tons of files. In order to work with autotools, just seven files are needed, which I have named "pupnp-creator.*" Of these, the real pain is the file "pupnp-creator.creator.user", which among other nuisances, has an unique identifier that depends on your system, gets to be updated with the date when you opened the IDE and some absolute paths in your system. So yes, I agree that these files suck, were not meant to be used under version control and have no real use for anyone not using qtcreator, but this tool is something I cannot afford not to use, and it is a mess to reconfigure it properly every time i do a git clone.

So, tell me what you think about this proposal: we move these files to a subfolder. Lets call it ide/qtcreator. I can put there a script to copy the files to the proper place and I can also "gitignore" them in the root. The can of worms can be kept under control, because I do invite anyone interested in using another IDE to create another subfolder, like ide/vscode or ide/vi and do the same.

Would that be ok or do you have any improvement on that idea?

Best regards,
Marcelo.

**Comment by ePirat** [comment]
That sounds like a good compromise to me

**Comment by whyman** [comment]
You should try out CLion, which supports autotools nowadays (https://blog.jetbrains.com/clion/2020/06/makefile-projects-in-clion/)

**Comment by mrjimenez** [comment]
Interesting, I will evaluate that, thanks Ian!

**Comment by mrjimenez** [comment]
Can we close this one? IDE files are now under the `ide` folder.

**Comment by ePirat** [comment]
Sure, thanks!
