### ISSUE TITLE
Using classes and objects in the library code

### ISSUE THREAD

**Issue by ingo-h** [pupnp/pupnp#248]
The UPnP protocol specification recommends to write code in an object oriented way. So I ask if it is possible to also use classes and objects for the code of the library. I don't think about to rewrite the whole library at once. There is to much know how into the code. But it may be possible to pick up subroutines/functions and rewrite them as classes. Together with Unit testing we could ensure that the behavior does not change. So we could do a step by step refactoring to use OOP. What do you think?

**Comment by mrjimenez** [comment]
Hi Ingo,

At this point, I don't see an advantage to do that. I told you before that I have though about rewriting it in C++, but then I thought for some time and didn't go ahead. The main reason (besides the lack of time) being that C++ usually generates a greater amount of code, while in C you have the opposite. Since the library is used in embedded systems, where memory footprint might be an issue, in the end I have chosen not to go through that path.

Your argument about unit test is good, but unit testing is also possible without C++, though certainly not as beautiful and easy.

Also, make no mistake: C++ is not C. I have dealt with both and it is much harder to understand what is really going on on C++. That extra not always fully understandable complexity is a little hard to use on your advantage on smaller and simpler programs.

As I said on the other thread, I imagine it would be a very nice code to write if properly modeled. But I also imagine it would be a total rewrite of the library.

I really do not want to discourage you, because I believe that people see things in different ways and have different experiences, and you might be seeing something amazing that I am not seeing. So I would like to add that if you still believe OOP would fit some subsystem of libupnp, definitely go for it. Worst case scenario you have a friendly fork of the project. And at the same time, best case scenario it will eventually become the new maintained one. Open source is all about that.

If you decide to go that way, there are some places where you can start. A long time ago I decided to create some C-like classes. You can have a look at them in `upnp/inc/Upnp*.h`. These files are mostly automatically generated by another program called `generator.c`. Not a long time ago, those classes were preprocessor generated, but the result was kinda messy and now the old templates are gone. These classes are far from incomplete, they are just the basic functionality I did in order to avoid rewriting the same code over and over again. Maybe you could rewrite one of these classes in C++ and see what the generated code looks like and behave in terms of size and speed. If you can show that there is an advantage, I am sure that people will support it.

Best regards,
Marcelo.

**Comment by Vollstrecker** [comment]
Why not just create a header for a class, maybe a little cpp that capsules all the handlers, does inits and that stuff and can be used as normal class. Let's call it libupnp-cpp which then itself links and uses the normal c-functions in the original lib. So the embedded teams can use libupnp directly with the small footprint, and the cpp users can use libupnp-cpp with the techniques they are used to and this one then uses libupnp. Should be possible with just one codebase with some little additions.

**Comment by ingo-h** [comment]
Hello Marcello,
I'm also active at [Raspberry Pi](https://raspberrypi.stackexchange.com/users/79866/ingo) so I really understand your argument to have a library with a small footprint. I wasn't aware that it is mainly used for embedded systems. I never thought about forking. Its not my intention to reinvent the wheel. I come to here because I'm looking for a stable upnp library supporting IPv6 only for my media project with RasPis. I also see it as an opportunity to better understand upnp and multicasting. So I would like to just continue with helping to improve IPv6 on the existing code base. OK, I have some suggestions belonging to that, but its to early for now without knowing more details about the library.

**Comment by mrjimenez** [comment]
Hi @ingo-h ,

I have been thinking a lot about what you wrote, and maybe there are some good reasons to switch to C++. This is more a brainstorm, but lets see:

1. We could, for a starter, compile the library using the C++ compiler and change things little by little. I understand that this is your original proposal and more or less on the same lines of what @Vollstrecker suggested.
2. There are already plenty of object like structures in the library. Those would be easily converted to C++ and would certainly benefit. Just look at generator.c.
3. We have recently found a major bug in IXML, which is a rather problematic code. There is a [neat substitute candidate](https://github.com/leethomason/tinyxml2) suggested in #249, but it is C++.
4. The concern about the library size could be evaluated, validated or rejected after the C++ compilation.

What do you think?

**Comment by Vollstrecker** [comment]
> We could, for a starter, compile the library using the C++ compiler and change things little by little.
This starter will stop you quite early. You can add
'''set_source_files_properties (${UPNP_SOURCES} PROPERTIES LANGUAGE CXX )
at line 84 of upnp/CMakeLists and it will error out at just the first file. But yes, this will help you changing the things little by little.

>We have recently found a major bug in IXML
When dropping ixml I would suggest to make big version-bump to syncronize the package and lib version. As this could be called a mayor change, I would go for 2. This would allow us to drop around 20 lines from that unreadable block in lines 8-76 in CMakeLists.txt. Dropping autoheader in this process would allow to drop this block completely.

>The concern about the library size could be evaluated, validated or rejected after the C++ compilation.
The stripped version has 368Kb, even if we get 50% overhead I thinks it's toleratable, as in embedded environments the memory sizes also have grown over the last decade.

Also I think, as this change requires (just a rough guess) some work at the progs using the lib, a libname to solve the other problem isn't a big issue then, too.

**Comment by ingo-h** [comment]
Hi @mrjimenez

> 1. We could, for a starter, compile the library using the C++ compiler

That is the requirement for everything. We should not do big changes during this process. The libray should compile in its current state. I have already tried it using std=c++11 but got mostly errors about types and casts. Its just some formal handwork to fix it, I think.

> and change things little by little. I understand that this is your original proposal and more or less on the same lines of what @Vollstrecker suggested.

Yes it is. We should prommise that the interfaces and calls for users does not change until we find that the refactoring is finished so far. With Unit testing we can provide it.

> 2. There are already plenty of object like structures in the library. Those would be easily converted to C++ and would certainly benefit. Just look at generator.c.

I will do.

> 4. The concern about the library size could be evaluated, validated or rejected after the C++ compilation.

I had a somewhat deeper look at th upnpapi.c module. There are always conditions to select between IPv4, IVv6 and IPv6UlaGua. I guess that's about a quarter of the code and could be reduced with splitting into these conditions at a very early step and have its own paths or polymorphic objects to handle this.

After compiling the library with g++ -std=c++11 (or newer standard?) I would start by wrapping the global library calls into an interface, for example with **UpnpInit2**:

    class IUpnpInit2 {
    public:
        virtual ~IUpnpInit2() {}
        virtual int UpnpInit2(const char* IfName,
                              unsigned short DestPort) = 0;
    };

Now we simply code against this interface. This ensures our promise not to change the interface and it is an important detail for unit testing.

    class CUpnpInit2 : public IUpnpInit2 {
    public:
        virtual ~CUpnpInit2() {}
        int UpnpInit2(const char* IfName,
                      unsigned short DestPort) override {
        // Existing code of UpnpInit2 without changes
        }
    };

    // compatible call
    int UpnpInit2(const char* IfName, unsigned short DestPort)
    {
        CUpnpInit2 upnpInit2Obj;
        return upnpInit2Obj.UpnpInit2(IfName, DestPort);
    }

If desired by the user, the class CUpnpInit2 can also be used as shown in the wrapper function.

> What do you think?

We should do it ;-)

**Comment by mrjimenez** [comment]
Hi @ingo-h ,

The new branch `reentrant` that I created has all the global library state collected into the `UpnpLib` object, so it is definitely worth a look.

In spite of that, I see two things to consider:

- `reentrant` may not be a good place to branch because of the interface changes. These are mostly the inclusion of the `UpnpLib *` pointer that acts like the `this *` pointer.
- On the other hand, it can be a good place to branch because the acessor functions (aka `members` :laughing: ) to access the old global state are already in place.

Have a look and tell me what you think. The branch already compiles in C and passes the old autotools tests.

**Comment by ingo-h** [comment]
Hi @mrjimenez,

I had a brief look at the generator.c and some functions. Most of them have now a `UpnpLib *p` LibraryHandle but I'm failing to see the idea. There are no class types or are there macros working?

**Comment by mrjimenez** [comment]
Hi @ingo-h ,

Remember that this is C. The purpose of generator.c is to reuse code that should be repeated many times around the library, i.e., write it only once. So there are those "classes":

```c
static struct s_Class my_classes[] = {
        INIT_CLASS(UpnpActionComplete),
        INIT_CLASS(UpnpActionRequest),
        INIT_CLASS(UpnpDiscovery),
        INIT_CLASS(UpnpEvent),
        INIT_CLASS(UpnpEventSubscribe),
        INIT_CLASS(UpnpExtraHeaders),
        INIT_CLASS(UpnpFileInfo),
        INIT_CLASS(UpnpLib),
        INIT_CLASS(UpnpStateVarComplete),
        INIT_CLASS(UpnpStateVarRequest),
        INIT_CLASS(UpnpSubscriptionRequest),
        INIT_CLASS(GenlibClientSubscription),
        INIT_CLASS(SSDPResultData),
        INIT_CLASS(TestClass),
};
```

Each of them has their members, e.g.:
```c
static struct s_Member SSDPResultData_members[] = {
        INIT_MEMBER(Param, TYPE_CLASS, UpnpDiscovery, "UpnpDiscovery.h", 0),
        INIT_MEMBER(Cookie, TYPE_INTEGER, void *, 0, 0),
        INIT_MEMBER(CtrlptCallback, TYPE_INTEGER, Upnp_FunPtr, "Callback.h", 0),
};
```

There are six possible types:
```c
enum e_Type
{
        TYPE_CLASS = 0,
        TYPE_INTEGER,
        TYPE_BUFFER,
        TYPE_LIST,
        TYPE_STRING,
        TYPE_DOMSTRING
};
```

A `TYPE_CLASS` is actualy something that generator.c has generated. I keep a `TestClass` in there to illustrate the usage:

```c
static struct s_Member TestClass_members[] = {
        INIT_MEMBER(TheList, TYPE_LIST, 0, 0, 0),
        INIT_MEMBER(TheInteger, TYPE_INTEGER, int, 0, 0),
        INIT_MEMBER(TheUnsignedLong, TYPE_INTEGER, unsigned long, 0, 0),
        INIT_MEMBER(TheCharPointer, TYPE_INTEGER, char *, 0, 0),
        INIT_MEMBER(TheBuffer, TYPE_BUFFER, struct TheStruct, "TheStruct.h", 0),
        INIT_MEMBER(TheActionComplete,
                TYPE_CLASS,
                UpnpActionComplete,
                "UpnpActionComplete.h",
                0),
        INIT_MEMBER(TheString, TYPE_STRING, 0, 0, 0),
        INIT_MEMBER(TheDomString, TYPE_DOMSTRING, 0, 0, 0),
};
```

Code is generated "automatically", you just have to describe the structures you will be working with.

```bash
cd upnp/generator
make && && ./generator && ./compile.sh
```

Keep in mind that when I started maintaining libupnp, there were lots of duplicated code, sometimes with duplicated bugs. Not to mention that some of the library interface was done directly through variables. The last part is particularly harmful for the developers, since exposing the internal state of the lib becomes an API. So now libupnp exposes no raw variables, only opaque handles and functions. That way we are free to change the implementation without breaking the user API.

The first version of this generator code was done using macros, abusing of a pattern called [`xmacros`](https://en.wikipedia.org/wiki/X_Macro). They worked fine but were a nightmare to maintain. Not a long time ago I decided to change it to a plain C executable to generate the necessary code. That is much easier to maintain.

The `UpnpLib *p` pointer is the opaque handler to the library, and was introduced in the `reentrant` branch. That eliminates the global state of the library. And opens some possibilities. For a maybe silly example, you can have two different control points bound to two different interfaces. Any of the global variables in the `upnpapi.c` file will now be part of the client.

**Comment by Vollstrecker** [comment]
> Yes it is. We should prommise that the interfaces and calls for users does not change until we find that the refactoring is finished so far. With Unit testing we can provide it.

Just to step back on this point. As this happens in different branches, the danger is very little. But I dislike ideas like "Do everything in a branch, then merge to master and release". In the branch the basics should be laid out and somewhere around 70-80% it should go into master to get maybe a wider testing, as many projects (not so many in case of this lib) just watch master.

Will this break things for users: Sure.
Is this bad: Nope, if users want a stable interface, they have to use the stable release.

If users use master, then to react on changes to be ready when it get's released, so give them the time. Most dev's that I know don't follow different branches as they just never know if it's relevant for the next release or the one after it, sometimes the idea get's abandoned at all, sometimes half of the things is dropped and implemented different, so it would be a waste of time. Inclusion in master is in that case some sort of "Not done yet, but basically the thing we end up with"

**Comment by mrjimenez** [comment]
Since we now have #260 , I think we can do everything on `master` because the changes were close to none.

I can put #260 on top of master, instead of  on top of #255 and start developing the next release using mixed C/C++.

**Comment by ingo-h** [comment]
I don't know how to put it, but I'm not entirely happy with the general change across the whole library. I was hoping to change things step by step and having tests for each step and to use the features of C++ like inheritance, interfaces, overriding, polymorphism, and so on.

By the way. I also have problems with cmake integration into the gtest paths: https://github.com/ingo-h/pupnp/actions/runs/662528165
@Vollstrecker can you please remove that cmake stuff from the gtest paths as long as the tests are not ready to be usable for pull requests?

**Comment by mrjimenez** [comment]
> I don't know how to put it, but I'm not entirely happy with the general change across the whole library. I was hoping to change things step by step and having tests for each step and to use the features of C++ like inheritance, interfaces, overriding, polymorphism, and so on.

I thought this was exactly what we are doing. #260 shows that we can start using C++ right now and change things step by step without a major break. The #260 commit is what I believed to be point number one above: 

> 1. We could, for a starter, compile the library using the C++ compiler

Notice that only `upnpapi.c` has been renamed to `upnpapi.cpp` and this is the only file being compiled with C++. That is the necessary change we need to start using C++ code, since this is the library's entry point.

I was thinking about committing just the last commit of #260 so that you can work on these gradual changes and leave the decision about library handles for later.

Maybe you can be more specific about what is bothering you, maybe I have misunderstood something. Nothing has been committed to the `master` branch, so nothing has changed yet.

> By the way. I also have problems with cmake integration into the gtest paths: https://github.com/ingo-h/pupnp/actions/runs/662528165
> @Vollstrecker can you please remove that cmake stuff from the gtest paths as long as the tests are not ready to be usable for pull requests?

**Comment by mrjimenez** [comment]
I guess we can close this issue, then. It is now officially allowed to use C++ in the project.

Since I have reopened, I will close it now. If someone still has anything to add, feel free to reopen.
